### ISSUE TITLE
Use different database for MSSQL in Docker Compose

### ISSUE THREAD

**Issue by arogachev** [yiisoft/data-db#83]
The database used currently - `tempdb`. This can cause problems in testing code like this - https://github.com/yiisoft/db-mssql/blob/9e7ca32060d8882498fff9ea41461caa8aa1a32d/src/Command.php#L31.

Approach:

```yml
services:
  php:
    depends_on:
      mssql-init:
        condition: service_completed_successfully
  mssql:
    # ...
  mssql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    network_mode: service:mssql
    command: >
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd"
      -Q "IF EXISTS (SELECT * FROM sys.databases WHERE name = 'yii') BEGIN DROP DATABASE yii END" -b -C
    depends_on:
      mssql:
        condition: service_healthy
```

Error:

```
Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'yii'.
```

Also running tests seems to be slower.

Low priority.
